<?php

/**
 * @file
 */

define('IMPORTANT_INFORMATION_FOOTER_EXPANDED_PERCENT_DEFAULT', 80);
define('IMPORTANT_INFORMATION_FOOTER_COLLAPSED_PERCENT_DEFAULT', 30);


/**
 * Implements hook_theme().
 */
function important_information_theme() {
  return [
    'important_information_sidebar' => [
      'variables' => ['info_prefix' => NULL, 'info suffix' => NULL, 'information' => NULL, 'modal' => NULL],
    ],
    'important_information_floating_container' => [
      'variables' => ['information' => NULL, 'modal' => NULL, 'expandable' => NULL, 'default_expand_markup' => NULL, 'info_prefix' => NULL, 'info suffix' => NULL ],
    ],
    'important_information_bottom' => [
      'variables' => ['info_prefix' => NULL, 'info suffix' => NULL, 'information' => NULL],
    ],
    'important_information_acknowledgment_modal' => [
      'variables' => ['information' => NULL, 'title' => NULL],
    ],
    // TODO:  delete this??
    'important_information_modal' => [
      'variables' => ['information' => NULL],
    ],
  ];
}