# Schema for the configuration files of the Important Information module.

# This schema tells the config system how to read our config YML files.
# See for example the file config/important_information.important_information_config.content.yml, which
# contains our default config entity.

# Documentation for schema files like this one is located here:
# https://drupal.org/node/1905070

important_imformation.important_information_config_entity.*:
  type: config_entity
  label: 'Important Information Configuration Entity'
  mapping:
    id:
      type: string
      label: 'II Config Entity ID'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    floopy:
      type: boolean
      label: 'Floopy'
    langcode:
      type: string
      label: 'Default language'
